controllers/NoteController.php
<?php

namespace app\controllers;

use app\models\Access;
use Yii;
use app\models\Note;
use app\models\search\NoteSearch;
use app\models\NoteQuery;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * NoteController implements the CRUD actions for Note model.
 */
class NoteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            
        ];
    }

    /**
     * Lists all Note models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new NoteSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /*
     * б) Сделать экшен my, выполнив у $query датапровайдера созданный
     * в пункте "а" метод byCreator($userId) и подставив вместо $userId Id текущего юзера.
     */

    public function actionMy()
    {
        $searchModel = new NoteSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        /** @var $query NoteQuery**/
        $query = $dataProvider->query;

        $query->byCreator(Yii::$app->user->id);

        return $this->render('my', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Note model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Note model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */

    /*
     * В методе actionCreate назначить значение id текущего пользователя свойству модели creator_id после ее создания и
     * поменять редирект после создания на созданный список своих заметок.
     */
    public function actionCreate()
    {
        $model = new Note();

        $model->creator_id = Yii::$app->user->id;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['my']);
//            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Note model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */

    /*
     * ж) Доработать безопасность - настроить поведение AccessControl и
     * проверку автора заметки в экшенах изменения и удаления.
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->creator_id !== Yii::$app->user->id) {
            throw new ForbiddenHttpException();
        }

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Note model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);

        if ($model->creator_id !== Yii::$app->user->id) {
            throw new ForbiddenHttpException();
        }

        $model->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Note model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Note the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Note::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/TestController.php
<?php
/*
 *  2) Настроить в web.php компонент test с ключом class равным \app\components\TestService::class,
 *  выполнить в TestController-е метод компонента test, передать результат выполнения во вьюху и там вывести.
 */

namespace app\controllers;

use app\models\Product;
use Yii;
use yii\helpers\VarDumper;
use yii\web\Controller;
use yii\db\Query;


class TestController extends Controller
{

    public function actionIndex()
    {
        
        return \Yii::$app->test->get();


        $test = new TestService();
        $test->attr = 'value';
        return $test->get();
        $product = new Product();
        
        $product->id = 1;
        $product->name = 'test product';
        $product->description = 'description';
        $product->category_id = '1';
        $product->price = '$100.00';
        
        return $this->render('index', ['product' => $product]);
    }
/*
 * 3) В экшене insert TestController-а через
 * Yii::$app->db->createCommand()->insert() вставить несколько записей в таблицу user,
 * $connection->createCommand()->insert('user', [
 */
    public function actionInsert() {

        Yii::$app->db->createCommand()->insert('user', [
            'username' => 'test username',
            'name' => 'test name',
            'password_hash' => 'testhash'
        ])->execute();

    }
/*
 * 4) Используя \yii\db\Query в экшене select TestController выбрать из user:
а) Запись с id=1
б) Все записи с id>1 отсортированные по имени (orderBy())
в) количество записей.
Выборку можно вывести просто через VarDumper или функцию _end() если подключили funcs.php.
 */

    /*
     * 6) Используя \yii\db\Query в экшене select TestController-а вывести содержимое note
с присоединенными по полю creator_id записями из таблицы user (innerJoin())
     */
    public function actionSelect() {

        $dbQuery1 = new Query();
        $dbQuery2 = new Query();
        $dbQuery3 = new Query();
        $dbQuery4 = new Query();

        $query1 = $dbQuery1->select('*')->from('user')->where(['id' => '10'])->all();
        $query2 = $dbQuery2->select('*')->from('user')->where(['>', 'id', '4'])->limit(6)->orderBy(['name' => SORT_DESC])->all();
        $query3 = $dbQuery3->select('*')->from('user')->count();

        $query4 = $dbQuery4->select('*')->from(['n' => 'note'])->innerJoin(['u' => 'user'], 'n.creator_id=u.id')->all();

        _dump($query1);
        _dump($query2);
        _dump($query3);
        _dump($query4);

    }

    /*
     * 5) В экшене insert TestController-а через Yii::$app->db->createCommand()->batchInsert() вставить одним вызовом сразу 3 записи в таблицу note,
в поле creator_id подставив реальное значение id из user.
     */

    public function actionInsertbatch() {

        Yii::$app->db->createCommand()->batchInsert('note', ['text', 'creator_id', 'created_at'], [
            ['text test 1', 20, mktime()],
            ['text test 2', 30, mktime()],
            ['text test 3', 40, mktime()]
        ])->execute();

        $dbQuery = new Query();

        $query = $dbQuery->select('*')->from('note')->all();
        _dump($query);

    }

}

controllers/_UserController.php
<?php
/*
 * В UserController создать экшен test, в нем используя ActiveRecord, т.е. методы классов User и Note,
выполнить последовательно, наблюдая выполняемые запросы в debug-панели:
а) Создать запись в таблице user.
б) Создать три связаные (с записью в user) запиcи в note, используя метод link().
в) Прочитать из базы все записи из User применив жадную подгрузку связанных данных из Note, с запросами без JOIN.
г) Прочитать из базы все записи из User применив жадную подгрузку связанных данных из Note, с запросом содержащем JOIN.
 */

namespace app\controllers;

use app\models\Access;
use app\models\Note;
use app\models\User;
use Yii;
use yii\helpers\VarDumper;
use yii\web\Controller;


class UserController extends Controller
{

	public function actionTest()
	{

		/*Создать запись в таблице user

		/*$user = new User();
		$user->name = 'User3';
		$user->username = 'User3';
		$user->password_hash = 'hash3';
		_dump($user->save());
		*/

		/*б) Создать три связаные (с записью в user) запиcи в note, используя метод link().

		$user = User::findOne(['name' => 'User1']);
		$note = new Note();
		$note->text = 'New note2 text';
		$note->created_at = mktime();
		$note->link('creator',$user);

		_dump($user->notes);
		*/

		//в) Прочитать из базы все записи из User применив жадную подгрузку связанных данных из Note, с запросами без JOIN.*/

//		$user = User::find()->with(User::RELATION_NOTES)->where(['name' => 'User1'])->one();

		//г) Прочитать из базы все записи из User применив жадную подгрузку связанных данных из Note, с запросом содержащем JOIN.

//		$user = User::find()->joinwith(User::RELATION_NOTES)->where(['name' => 'User1'])->one();


//		6) Добавить с помощью созданного релейшена связь между записями в User и Note (метод link(), обе модели д.б. сохранены).


		$user = User::findOne(['name' => 'User1']);
		$note = Note::findOne(28);


		$user->link(User::RELATION_NOTES_ACCESS, $note);
		
		$user = User::find()->with(User::RELATION_NOTES, User::RELATION_ACCESS)->where(['name' => 'User1'])->one();


		return $this->renderContent(
			VarDumper::dumpAsString($user, 4, true)
		);


	}

}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    /*
     * В меню сайта убираем ссылки about-contact и делаем ссылки на создание заметки и
     * список своих заметок, можно добавить ссылки на список расшаренных и доступных заметок.
     */
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Home', 'url' => ['/site/index']],
            ['label' => 'Мои заметки', 'url' => ['/note/my']],
            ['label' => 'Создать Заметку', 'url' => ['/note/create']],
//            ['label' => 'About', 'url' => ['/site/about']],
//            ['label' => 'Contact', 'url' => ['/site/contact']],
//            ['label' => 'Products', 'url' => ['/product']],
//            ['label' => 'TestController', 'url' => ['/test/index']],
//            ['label' => 'TestController Insert', 'url' => ['/test/insert']],
//            ['label' => 'TestController Insert Batch', 'url' => ['/test/insertbatch']],
//            ['label' => 'TestController Select', 'url' => ['/test/select']],
//            ['label' => 'UserController test', 'url' => ['/user/test']],
            Yii::$app->user->isGuest ? (
                ['label' => 'Login', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>